up/%:
	sudo docker compose -f docker-compose-common.yml -f docker-compose-node.yml up -d --build

down/%:
	sudo docker compose -f docker-compose-common.yml -f docker-compose-node.yml down --volumes


